/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'

import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedExerciseSlugRouteImport } from './routes/_authenticated/exercise.$slug'
import { Route as AuthenticatedSummarySessionIdRouteImport } from './routes/_authenticated/summary.$sessionId'
import { Route as AuthenticatedWorkoutDayIdRouteImport } from './routes/_authenticated/workout.$dayId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciseSlugRoute =
  AuthenticatedExerciseSlugRouteImport.update({
    id: '/exercise/$slug',
    path: '/exercise/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSummarySessionIdRoute =
  AuthenticatedSummarySessionIdRouteImport.update({
    id: '/summary/$sessionId',
    path: '/summary/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutDayIdRoute =
  AuthenticatedWorkoutDayIdRouteImport.update({
    id: '/workout/$dayId',
    path: '/workout/$dayId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/exercise/$slug': typeof AuthenticatedExerciseSlugRoute
  '/summary/$sessionId': typeof AuthenticatedSummarySessionIdRoute
  '/workout/$dayId': typeof AuthenticatedWorkoutDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/exercise/$slug': typeof AuthenticatedExerciseSlugRoute
  '/summary/$sessionId': typeof AuthenticatedSummarySessionIdRoute
  '/workout/$dayId': typeof AuthenticatedWorkoutDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/exercise/$slug': typeof AuthenticatedExerciseSlugRoute
  '/_authenticated/summary/$sessionId': typeof AuthenticatedSummarySessionIdRoute
  '/_authenticated/workout/$dayId': typeof AuthenticatedWorkoutDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/library'
    | '/progress'
    | '/settings'
    | '/today'
    | '/exercise/$slug'
    | '/summary/$sessionId'
    | '/workout/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/library'
    | '/progress'
    | '/settings'
    | '/today'
    | '/exercise/$slug'
    | '/summary/$sessionId'
    | '/workout/$dayId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/library'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/exercise/$slug'
    | '/_authenticated/summary/$sessionId'
    | '/_authenticated/workout/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise/$slug': {
      id: '/_authenticated/exercise/$slug'
      path: '/exercise/$slug'
      fullPath: '/exercise/$slug'
      preLoaderRoute: typeof AuthenticatedExerciseSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary/$sessionId': {
      id: '/_authenticated/summary/$sessionId'
      path: '/summary/$sessionId'
      fullPath: '/summary/$sessionId'
      preLoaderRoute: typeof AuthenticatedSummarySessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workout/$dayId': {
      id: '/_authenticated/workout/$dayId'
      path: '/workout/$dayId'
      fullPath: '/workout/$dayId'
      preLoaderRoute: typeof AuthenticatedWorkoutDayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedExerciseSlugRoute: typeof AuthenticatedExerciseSlugRoute
  AuthenticatedSummarySessionIdRoute: typeof AuthenticatedSummarySessionIdRoute
  AuthenticatedWorkoutDayIdRoute: typeof AuthenticatedWorkoutDayIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedExerciseSlugRoute: AuthenticatedExerciseSlugRoute,
  AuthenticatedSummarySessionIdRoute: AuthenticatedSummarySessionIdRoute,
  AuthenticatedWorkoutDayIdRoute: AuthenticatedWorkoutDayIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
